DB_USER = "joya_user"
DB_PASSWORD = "joya123"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "joyastack_db"

SQLALCHEMY_DATABASE_URI = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

